# Generated by Django 6.0.6 on 2026-07-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('-is_default', 'label'), 'verbose_name_plural': 'Addresses'},
        ),
    ]
